Repository Dwolla/dev-portal, pull requests merged in 2022-05, with the labels that each got.

#340 DEV-894: Add `hideZeroBalance` optional attribute for balance display component
  pages/concepts/drop-in-components.mdx
Labels: documentation

#342 DEV-516: Update Transfer Failures to include debit/credit information for ACH returns
  pages/concepts/transfer-failures.mdx
Labels: documentation

#345 DEV-905: Webhooks: Header names correction
  pages/changelog.mdx
  pages/concepts/webhook-events.mdx
  pages/guides/webhooks/validating-webhooks.mdx
Labels: documentation

#344 DEV-854: Add `ScanIdUnrecognized` document failure reason
  pages/api-reference/documents/index.mdx
  pages/changelog.mdx
  pages/guides/business-verified-customer/handle-verification-statuses.mdx
  pages/guides/personal-verified-customer/handle-verification-statuses.mdx
Labels: documentation

#350 DEV-830: Disable UCR Balance option in Transfer Workflow, and automatically disable Receiver until Sender is set
  app/components/base/FundsFlowSelector.tsx
  app/components/base/TransferWorkflow.tsx
Labels: enhancement

#349 DEV-904: Update Storybook to latest version & use Webpack 5
  .storybook/main.js
  .storybook/webpack.config.js
  package.json
  yarn.lock
Labels: bug, dependencies

#352 DEV-928: Overhaul Webhooks Guide
  pages/api-reference/webhook-subscriptions/create.mdx
  pages/api-reference/webhooks/index.mdx
  pages/concepts/webhook-events.mdx
  pages/guides/transfer-money-me-to-me/index.mdx
  pages/guides/webhooks/create-subscription.mdx
  pages/guides/webhooks/frequently-asked-questions.mdx
  pages/guides/webhooks/index.mdx
  pages/guides/webhooks/process-validate.mdx
  pages/guides/webhooks/process-webhooks.mdx
  pages/guides/webhooks/validating-webhooks.mdx
Labels: documentation

#351 DEV-933: Begin removing references to IAV in preperation for deprecation
  pages/api-reference/events/index.mdx
  pages/concepts/bank-funding-source.mdx
  pages/concepts/debit-cards.mdx
  pages/concepts/drop-in-components.mdx
  pages/concepts/webhook-events.mdx
Labels: documentation

#353 DEV-889: Update microdeposit verification to include `failed-verification-micro-deposits` & link to embedded resources
  pages/guides/micro-deposit-verification/verify-micro-deposits.mdx
Labels: documentation
